apiVersion: monitoring.coreos.com/v1               # API version for the ServiceMonitor resource.
kind: ServiceMonitor                               # Defines a ServiceMonitor, used by Prometheus to scrape metrics from a specific service.
metadata:
  name: metrics-dev
  # Label linking this resource to the Prometheus Operator.
  labels:
    release: prometheus-operator  
spec:
  endpoints:
    - interval: 10s                                # Specifies how often Prometheus will scrape metrics from the target.
      path: /actuator/prometheus                   # The HTTP endpoint exposed by the service that provides metrics.
      port: http                                   # The port on the target service to scrape metrics from.
  selector:
  # Specifies how to find the target service whose metrics should be monitored.
    matchLabels:  
      app.kubernetes.io/instance: backend-metrics  # Matches the "instance" label of the target service.
      app.kubernetes.io/name: backend-metrics      # Matches the "name" label of the target service.